services:
  # 1. Main Web Service
  - type: web
    name: plagix-web
    runtime: docker
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: RUN_MIGRATIONS
        value: "true"
      - key: START_SCRAPE_ON_BOOT
        value: "true"
      - key: DB_CONNECTION
        value: pgsql # Or mysql

  # 2. Queue Worker (Runs in the background)
  - type: worker
    name: plagix-worker
    runtime: docker
    plan: free
    dockerCommand: php artisan queue:work --tries=3