on: 
  push: 
    branches: [main]

name: Deploy website on push

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      # Récupère le code source du dépôt GitHub dans le runner
      - name: Get latest code
        uses: actions/checkout@v4

      # Envoie les fichiers du dossier backend/ vers le serveur via FTP
      # Les fichiers sensibles (.env, vendor, .git) sont exclus
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /public/
          local-dir: ./
          exclude: |
            **/.git*
            **/.git*/**
            **/vendor/**
            **/.env

     ##ssh